// Single source of truth for all blog posts, following the same pattern as
// app/seo-pages/seoPages.js. `body` is an array of blocks rendered by
// components/BlogPostBody.js: plain strings are paragraphs, { h }, { list },
// and { quote } are subheading/bullet-list/pull-quote blocks respectively.

export const posts = [
  // ─── 2023 — Getting started ────────────────────────────────────────────
  {
    slug: "do-you-need-a-website",
    title: "Do You Actually Need a Website?",
    category: "Getting Started",
    metaDescription: "Not every small business needs a website, but most local trades lose work without one. Here's how to tell which camp you're in.",
    publishDate: "2023-08-10",
    readTime: 4,
    excerpt: "Not every small business needs a website. Here's a straight answer on which camp you're in.",
    body: [
      "It depends what kind of business you run. A website isn't a magic box that prints customers: it's a tool, and like any tool it's only worth having if it does a job you need done.",
      { h: "When you probably don't need one" },
      "If every job comes from word of mouth, repeat customers, or a trade account with other businesses, a website might add little. Plenty of small operators run for years on reputation alone.",
      { h: "When you almost certainly do" },
      "The moment someone searches \"[your trade] near me\" and finds three competitors but not you, you're losing jobs you'll never know you missed. That's the real cost of not having one: not looking unprofessional, but enquiries going to someone else because they were easier to find.",
      {
        list: [
          "You rely on new customers finding you, not just repeat business",
          "Competitors in your area show up on Google and you don't",
          "You want customers to be able to check you out before calling",
          "You're spending money on other marketing that has nowhere to send people",
        ],
      },
      "If two or more of those sound like you, a website isn't optional polish. It's the difference between being findable and being invisible to anyone who doesn't already know your name.",
    ],
  },
  {
    slug: "what-should-a-small-business-website-have",
    title: "What Should Every Small Business Website Have?",
    category: "Getting Started",
    metaDescription: "The essential elements every small business website needs: not a wishlist, a checklist of what gets you found and gets you calls.",
    publishDate: "2023-09-14",
    readTime: 5,
    excerpt: "Not a wishlist. A checklist of what needs to be there for a small business site to do its job.",
    body: [
      "Plenty of small business websites look fine and still don't work. The difference usually isn't design polish; it's whether a handful of basics are there.",
      { h: "The non-negotiables" },
      {
        list: [
          "A clear, working phone number, ideally clickable on mobile (tel: links)",
          "What you do and where you do it, in plain language, above the fold",
          "Real photos of your actual work, not stock images",
          "A way to get in touch that doesn't require an email client to open",
          "Your opening hours, if that's relevant to how customers reach you",
        ],
      },
      { h: "The things that quietly matter more than people think" },
      "A title tag and meta description that describe the page (not \"Home | Untitled Site\"), a mobile viewport so it doesn't look broken on a phone, and a fast load time. Most visitors on mobile data will bounce off a slow site before it finishes loading.",
      { h: "What you can skip, at least at first" },
      "A blog, a members area, live chat, a huge portfolio: none of these matter if the basics above aren't nailed first. Get found, get contacted, get the job. Everything else is optimisation on top of that.",
      "It's tempting to think a website needs to be impressive. Mostly it needs to be functional, fast, and honest about what you do; impressive is what happens once those are solid.",
    ],
  },
  {
    slug: "how-much-should-a-website-cost",
    title: "How Much Should a Website Cost?",
    category: "Getting Started",
    metaDescription: "What a small business website should cost in the UK, and what you're really paying for at different price points.",
    publishDate: "2023-10-05",
    readTime: 5,
    excerpt: "What you're really paying for at different price points, and where the real value differences show up.",
    body: [
      "This is the question everyone asks and almost nobody gets a straight answer to, mostly because \"a website\" covers everything from a £5/month template to a £15,000 custom build.",
      { h: "Roughly, the tiers look like this" },
      {
        list: [
          "DIY builder (Wix, Squarespace): £15-30/month, your own time to build it",
          "Freelancer one-off build: £300-1,500, usually no ongoing SEO",
          "Agency monthly plan: £50-150/month, build + hosting + ongoing SEO work",
          "Bespoke agency build: £2,000-15,000+, for larger or more complex sites",
        ],
      },
      { h: "What you're really paying more for" },
      "It's rarely just \"a nicer-looking site.\" The real differences: does anyone submit your sitemap to Google, is anyone checking it still works in six months, can you update it yourself without calling someone, and is your Google Business Profile connected to any of it. A cheap site with none of that can rank worse than a free one, because nobody ever told Google it exists.",
      { h: "The question that actually matters" },
      "Not \"what does it cost\" but \"what happens after it's built.\" A one-off payment with no ongoing SEO is fine if you just need a functioning site. If you want it to actively bring in more work over time, that's an ongoing job, not a one-time purchase, and pricing should reflect which one you're buying.",
    ],
  },
  {
    slug: "website-vs-facebook-page",
    title: "Website vs a Facebook Page: What's Actually Better?",
    category: "Getting Started",
    metaDescription: "A Facebook page is free and easy, so why do you need a website too? Here's what each one does for a local business.",
    publishDate: "2023-11-16",
    readTime: 4,
    excerpt: "A Facebook page is free and easy. Here's what it can't do that a proper website can.",
    body: [
      "A lot of local businesses run entirely on a Facebook page for years, and for some, that's fine. But it's worth being clear-eyed about what a Facebook-only presence can't do.",
      { h: "What a Facebook page is good at" },
      "It's free, it's quick to update, and if your customers are already on Facebook, posting there reaches people who already follow you. For word-of-mouth-driven local groups (community pages, local buy-and-sell groups), it can work well.",
      { h: "What it can't do" },
      {
        list: [
          "It won't rank in Google search results the way a real website can",
          "You don't own it: a policy change or account issue can take it away entirely",
          "It looks less credible to someone comparing you against a competitor with a proper site",
          "You can't add structured data, a proper sitemap, or any of the technical SEO that helps Google understand and trust your business",
        ],
      },
      "For most local trades: do both. Keep the Facebook page for quick updates and community reach, but have a real website as the thing that shows up when someone searches for what you do and where you do it, because that search is where most new customers, not existing followers, find you.",
    ],
  },
  {
    slug: "how-long-does-a-website-take",
    title: "How Long Does It Actually Take to Build a Website?",
    category: "Getting Started",
    metaDescription: "A realistic timeline for building a small business website: what causes delays, and how to keep things moving.",
    publishDate: "2023-12-07",
    readTime: 3,
    excerpt: "A realistic timeline for a small business website build, and what causes the delays.",
    body: [
      "For a straightforward small business site, 2-3 weeks from kickoff to launch is realistic if things move at a normal pace. That's not the time spent building; it's the calendar time, and the gap between those two numbers is almost always the same thing.",
      { h: "What causes delays" },
      {
        list: [
          "Waiting on photos, logo files, or copy from the business owner",
          "Slow turnaround on reviewing draft versions",
          "Changing scope partway through (adding pages, features not in the original plan)",
          "Domain or DNS issues that need a third party (registrar) to resolve",
        ],
      },
      "Notice none of those are \"the build itself takes ages\": a competent developer can build the actual site in days. The calendar time is almost entirely about how quickly information and feedback move back and forth.",
      { h: "How to keep it fast" },
      "Have your photos and key details ready before you start, respond to review requests within a day or two, and try to lock scope early rather than adding things mid-build. Do that, and 2-3 weeks is achievable, even for a business starting from nothing.",
    ],
  },

  // ─── 2024 — SEO fundamentals ────────────────────────────────────────────
  {
    slug: "what-is-local-seo",
    title: "What Is Local SEO and Why Does It Matter?",
    category: "SEO",
    metaDescription: "Local SEO explained simply: what it is, why it matters more than general SEO for most small businesses, and where to start.",
    publishDate: "2024-01-18",
    readTime: 5,
    excerpt: "What local SEO is, and why it matters more than general SEO for most small local businesses.",
    body: [
      "\"SEO\" gets thrown around as one big vague thing, but for a local business (a garage, a butcher, a recovery service) what matters is a specific subset of it called local SEO.",
      { h: "The difference" },
      "General SEO is about ranking for a search term anywhere in the world. Local SEO is about ranking when someone searches with a location attached: \"car recovery Glasgow,\" \"butchers near me,\" \"MOT test Erskine.\" For a business that only serves one area, that's almost the entire game.",
      { h: "What drives local rankings" },
      {
        list: [
          "A complete, verified Google Business Profile with the right categories",
          "Consistent name, address and phone number across your site and any directories",
          "Google reviews, both the count and how recent they are",
          "A website that clearly and repeatedly mentions the areas you serve",
          "Structured data (LocalBusiness schema) that tells Google exactly what you do and where",
        ],
      },
      { h: "Why it's worth the focus" },
      "General SEO for competitive national terms can take years and huge budgets to move. Local SEO, for a specific town or trade, is a much smaller pond, which means the effort required to rank well is far more achievable for a business with no marketing team and a modest budget.",
    ],
  },
  {
    slug: "google-business-profile-explained",
    title: "What Is a Google Business Profile and Do You Need One?",
    category: "SEO",
    metaDescription: "Google Business Profile explained: what it is, why it's free, and why it's one of the highest-impact things a local business can set up.",
    publishDate: "2024-02-15",
    readTime: 4,
    excerpt: "The free listing most local businesses either haven't claimed or aren't using properly. Here's why it matters.",
    body: [
      "If you've ever searched a local business and seen a box on the right with their star rating, opening hours, photos, and a map pin, that's their Google Business Profile (formerly Google My Business). It's free, and for a local business it's one of the highest-leverage things you can set up properly.",
      { h: "Why it matters so much" },
      "For local searches, Google often shows the \"local pack\": three business listings with a map, above the normal search results entirely. Ranking there doesn't need a website at all in the strictest sense, though a connected website helps significantly.",
      { h: "What needs doing" },
      {
        list: [
          "Claim and verify the listing (postcard, phone, or email verification)",
          "Pick the right primary category and add relevant secondary categories",
          "Add real photos of the business, the team, and the work itself",
          "Keep opening hours accurate, especially around holidays",
          "Respond to reviews, good and bad",
        ],
      },
      "The businesses that treat this as a one-time setup task usually underperform the ones that treat it as a living profile: posting updates, adding new photos, and staying active. Google rewards activity, not just existence.",
    ],
  },
  {
    slug: "why-website-not-showing-on-google",
    title: "Why Isn't My Website Showing Up on Google?",
    category: "SEO",
    metaDescription: "The most common, fixable reasons a small business website isn't appearing in Google search results.",
    publishDate: "2024-03-14",
    readTime: 5,
    excerpt: "The most common, and fixable, reasons a website simply isn't showing up in search at all.",
    body: [
      "This is one of the most common questions from business owners with a working site that just... isn't findable. Usually it's one of a small handful of causes, most of them fixable in minutes once identified.",
      { h: "The usual suspects" },
      {
        list: [
          "A noindex tag accidentally left on from a staging/testing phase: this literally tells Google not to show the page",
          "No sitemap.xml submitted to Google Search Console, so Google hasn't fully discovered every page",
          "The site is brand new: indexing can take days to a few weeks even when everything's right",
          "Thin or duplicate content that Google doesn't consider worth ranking",
          "The site loads fine for a human but renders empty for a search crawler (common with some JavaScript-heavy builds with no server-side rendering)",
        ],
      },
      { h: "How to check" },
      "Search \"site:yourdomain.com\" directly in Google. If nothing comes up, the site likely isn't indexed at all, which points to the noindex or sitemap issue rather than a ranking problem. Google Search Console (free) will also directly tell you if pages are indexed and flag specific issues.",
      "Being invisible and ranking poorly are different problems with different fixes, worth confirming which one you have before assuming it's a bigger issue than it is.",
    ],
  },
  {
    slug: "title-tags-meta-descriptions-explained",
    title: "Title Tags and Meta Descriptions Explained",
    category: "SEO",
    metaDescription: "What title tags and meta descriptions do, why they matter for click-through rate, and how to write good ones.",
    publishDate: "2024-04-11",
    readTime: 4,
    excerpt: "Two small details that punch well above their weight for both rankings and click-through rate.",
    body: [
      "These are two of the smallest pieces of a webpage, and two of the most disproportionately important for both ranking and getting clicked once you do rank.",
      { h: "The title tag" },
      "This is the blue clickable text in search results, and also what shows in the browser tab. It's one of the strongest on-page ranking signals Google uses, so it should clearly include the main service and the location: \"Mobile Car Detailing Glasgow | Business Name\" beats \"Home | Business Name\" by a wide margin.",
      { h: "The meta description" },
      "This is the grey text underneath the title in search results. It doesn't directly affect ranking the way the title does, but it's your pitch for why someone should click your result over the one above or below it. A vague or missing description means Google writes one for you, usually a random snippet of page text, not a pitch.",
      { h: "A simple rule of thumb" },
      { quote: "If a stranger saw only your title and description, would they know what you do, where, and why to pick you?" },
      "If not, that's the gap worth closing first, before touching anything more advanced.",
    ],
  },
  {
    slug: "what-is-a-sitemap",
    title: "What Is a Sitemap and Why Does It Matter?",
    category: "SEO",
    metaDescription: "Sitemap.xml explained simply: what it does, why search engines use it, and what it means if your site doesn't have one.",
    publishDate: "2024-05-09",
    readTime: 3,
    excerpt: "The unglamorous file that quietly helps search engines find and re-crawl your pages faster.",
    body: [
      "A sitemap.xml is a simple file listing every page on your site, submitted to Google (and other search engines) so they know exactly what exists without having to discover it purely by following links.",
      { h: "Why it matters" },
      "For a small site, Google will usually find your pages eventually just by crawling links. But a sitemap speeds that up significantly, and matters much more once a site has more than a handful of pages, or gets updated regularly: new blog posts, new location pages, seasonal changes.",
      { h: "What it doesn't do" },
      "It doesn't guarantee ranking, and it doesn't force Google to index everything on it. It's a hint, not a command, but it's a free, near-zero-effort hint that removes one possible reason a page takes longer than it should to show up in search.",
      "If you don't know whether your site has one, checking is simple: try visiting yourdomain.com/sitemap.xml directly. If it 404s, that's a fixable gap.",
    ],
  },
  {
    slug: "how-to-get-more-google-reviews",
    title: "How to Get More Google Reviews Without Annoying Customers",
    category: "Reviews",
    metaDescription: "Practical, non-pushy ways to get more Google reviews for a local business, and what Google's rules actually allow.",
    publishDate: "2024-06-13",
    readTime: 4,
    excerpt: "Practical, non-pushy ways to get more reviews, and what Google's rules actually allow you to do.",
    body: [
      "Review count and rating are among the strongest local ranking factors there are, but there's a right and wrong way to go after more of them.",
      { h: "What works" },
      {
        list: [
          "Ask at the exact moment satisfaction is highest, right after the job's done, not days later",
          "Send a direct link (not just \"leave us a review\"): friction kills conversion",
          "Text or WhatsApp tends to outperform email for response rate",
          "Make it a normal part of how every job wraps up, not an occasional ask",
        ],
      },
      { h: "What Google explicitly doesn't allow" },
      "Offering discounts or incentives in exchange for reviews, review gating (only asking happy customers while filtering out unhappy ones before they can post publicly), and fake or incentivised reviews generally. Google actively polices this, and getting caught can mean the whole profile gets suppressed or removed.",
      { h: "The realistic target" },
      "Consistency beats bursts. A steady trickle of new, genuine reviews every week reads to Google (and to customers) as an active, trustworthy business, far more than an old pile of reviews with nothing recent.",
    ],
  },
  {
    slug: "dealing-with-a-bad-google-review",
    title: "What to Do About a Bad Google Review",
    category: "Reviews",
    metaDescription: "How to handle a negative Google review professionally: what to say, what not to say, and when it's worth disputing.",
    publishDate: "2024-07-11",
    readTime: 4,
    excerpt: "How to handle a negative review professionally, and when it's worth trying to get it removed.",
    body: [
      "Everyone gets one eventually, even businesses doing everything right. What matters is how it's handled, because the review itself is only half the story: anyone reading it also reads your response.",
      { h: "The response that helps" },
      "Stay calm, acknowledge the specific complaint, and offer to sort it offline (a phone number, an email). Never argue in public, never get defensive, never accuse the reviewer of lying even if you think they are; future customers reading it will judge your response more than the original complaint.",
      { h: "When it's worth disputing" },
      {
        list: [
          "The review is clearly for a different business (wrong name, wrong location, wrong service entirely)",
          "It contains no actual customer experience: pure spam or a competitor",
          "It violates Google's content policies (harassment, hate speech, obviously fake)",
        ],
      },
      "Genuine but harsh reviews from real customers almost never get removed just because they're unflattering. Google's policy is deliberately narrow here, and that's the right call even when it's frustrating.",
      { h: "The long game" },
      "One bad review buried under thirty recent good ones barely registers. The best long-term defence against any single bad review is having enough recent, genuine positive ones around it.",
    ],
  },
  {
    slug: "why-review-count-matters",
    title: "Why Review Count Matters More Than You Think",
    category: "Reviews",
    metaDescription: "Why the number of Google reviews matters as much as (or more than) the star rating for local search rankings.",
    publishDate: "2024-08-08",
    readTime: 3,
    excerpt: "A 5.0 rating from 8 reviews and a 4.8 from 200 reviews aren't equally trusted. Here's why.",
    body: [
      "It's tempting to think a perfect star rating is the goal, full stop. In practice, review count matters at least as much, and past a certain point, more.",
      { h: "Why volume signals trust" },
      "A handful of 5-star reviews can be (rightly or wrongly) discounted by customers as friends and family. A large volume of reviews, even with an occasional 3 or 4 star among them, reads as a genuine, high-volume, trustworthy business. Google's ranking algorithm treats it similarly: both count and recency factor into local rankings, not just the average score.",
      { h: "The competitive reality" },
      "In most trades, the businesses winning the local pack aren't sitting on 15 reviews; they're often at 100, 300, sometimes 1,000+. A newer business with a perfect 5.0 from a dozen reviews is still, numerically, behind an established competitor with a slightly lower average but ten times the review count.",
      "The practical takeaway: don't stop once the rating looks good. Keep the review requests going as a routine part of the business, indefinitely. The count is a moving target competitors are working on too.",
    ],
  },
  {
    slug: "website-checklist-car-garages",
    title: "A Website Checklist for Car Garages and MOT Centres",
    category: "Industry Guides",
    metaDescription: "What a garage or MOT centre website needs to bring in bookings: a practical checklist, not generic advice.",
    publishDate: "2024-09-12",
    readTime: 4,
    excerpt: "What a garage or MOT centre website needs to bring in bookings, not just look presentable.",
    body: [
      "Garages have a specific set of things customers look for, and a generic small-business website template often misses most of them.",
      { h: "What customers are checking for" },
      {
        list: [
          "MOT class covered (Class 4, Class 7, etc.), stated clearly, not buried",
          "Current prices, or at least a starting price: price-shopping is common before someone calls",
          "Booking availability: a form or online booking beats \"call us\" for a lot of younger customers",
          "Whether they do both domestic and commercial vehicles",
          "Location and parking/drop-off details, since this is a physical-visit business",
        ],
      },
      { h: "The SEO angle specific to garages" },
      "\"MOT test [town]\" and \"car servicing near me\" are both extremely high-intent searches: someone typing that is close to booking, not just browsing. A garage site that doesn't clearly and repeatedly mention its specific location and services is leaving warm leads on the table.",
      "Real before/after or workshop photos also do more work here than generic stock imagery. Customers handing over a car want to see the actual place their vehicle is going.",
    ],
  },
  {
    slug: "marketing-a-vehicle-recovery-business",
    title: "Marketing a Vehicle Recovery Business Online: What Actually Works",
    category: "Industry Guides",
    metaDescription: "How vehicle recovery and breakdown businesses should approach their website and local SEO, built around how customers search in an emergency.",
    publishDate: "2024-10-10",
    readTime: 5,
    excerpt: "Recovery is an emergency-search business. The marketing playbook has to match that, not fight it.",
    body: [
      "Recovery is one of the more unusual categories to market, because the customer is often searching from the roadside, mid-emergency, on a phone, wanting one thing: someone who'll show up fast.",
      { h: "What that means for the website" },
      {
        list: [
          "The phone number needs to be the single most obvious thing on the page, not buried at the bottom",
          "Response time (\"30-45 min typical arrival\") is a genuine selling point if it's true",
          "A sticky mobile call button that's always visible, not just in a header that scrolls away",
          "Coverage area stated explicitly and specifically: town names, not just \"Central Scotland\"",
        ],
      },
      { h: "The SEO play that works especially well here" },
      "Individual pages for each town/area covered, each one mentioning specific local landmarks, road names, and motorway junctions, not just the town name repeated. \"Recovery near Erskine, covering the M8, Glasgow Airport and Bishopton\" tells Google (and the person searching) far more than a generic areas-we-cover list.",
      { h: "Reviews carry extra weight here" },
      "Someone choosing a recovery company at 11pm on the hard shoulder doesn't have time to compare five options in depth; they're picking fast, based on star rating and how many reviews back it up. This is a category where review volume directly and visibly affects who gets chosen.",
    ],
  },
  {
    slug: "booking-friendly-websites-valeting",
    title: "Why Mobile Valeting & Detailing Businesses Need Booking-Friendly Websites",
    category: "Industry Guides",
    metaDescription: "Why mobile car detailing and valeting businesses convert better with clear pricing and easy booking, not just a portfolio of finished cars.",
    publishDate: "2024-11-14",
    readTime: 4,
    excerpt: "A gallery of shiny cars looks nice, but pricing and easy booking are what actually convert.",
    body: [
      "Detailing and valeting websites often lean heavily on photo galleries of finished work, which matters, but isn't usually the thing standing between a visitor and a booking.",
      { h: "What gets someone to book" },
      {
        list: [
          "Clear package tiers with prices (e.g. Safe Wash from £30, Full Valet from £60)",
          "What's included at each tier, specifically: customers hate ambiguity about what they're paying for",
          "Mobile-to-your-driveway convenience stated clearly if that's the offer",
          "An easy way to check availability or request a slot, not just a phone number",
        ],
      },
      { h: "The pricing transparency question" },
      "Some businesses avoid listing prices, worried about scaring people off. In practice, the opposite is usually true for this category: someone comparing three local detailers will often just skip the one with no visible pricing and go straight to a competitor who made the decision easy.",
      { h: "Photos still matter, just not as the whole strategy" },
      "Real before/after shots of actual jobs (with permission) build trust fast, but they work best alongside clear pricing and booking, not as a substitute for it.",
    ],
  },
  {
    slug: "why-website-speed-matters",
    title: "Why Fast-Loading Websites Win More Customers",
    category: "SEO",
    metaDescription: "How page speed affects both search rankings and whether visitors stick around, and the usual causes of a slow site.",
    publishDate: "2024-12-05",
    readTime: 4,
    excerpt: "Page speed affects both rankings and whether visitors stick around long enough to convert.",
    body: [
      "A slow website loses customers twice: once when Google factors speed into rankings, and again when an actual visitor gives up waiting and leaves before the page finishes loading.",
      { h: "The usual culprits" },
      {
        list: [
          "Uncompressed, oversized images (a single photo can be several MB straight off a phone)",
          "Too many third-party scripts (chat widgets, trackers, embeds) loaded on every page",
          "No lazy-loading on images or embedded video below the fold",
          "Cheap or oversold hosting struggling under load",
        ],
      },
      { h: "The mobile reality" },
      "Most local business traffic is now mobile, often on patchy signal: someone searching for a plumber while standing in a flooding kitchen isn't on fast wifi. A site that's slow on a good connection is often unusable on a bad one, right at the moment intent is highest.",
      { h: "The good news" },
      "Speed problems are almost always fixable without a full rebuild. Compressing images and cutting unnecessary scripts alone often makes a dramatic difference; it's one of the highest-return, lowest-effort fixes available on most small business sites.",
    ],
  },

  // ─── 2025 — Conversion & choosing a designer ───────────────────────────
  {
    slug: "questions-to-ask-a-web-designer",
    title: "What Questions Should You Ask a Web Designer Before Hiring Them?",
    category: "Getting Started",
    metaDescription: "The questions worth asking any web designer before you commit: about SEO, ownership, hosting, and what happens after launch.",
    publishDate: "2025-01-16",
    readTime: 4,
    excerpt: "The questions that reveal what you're signing up for, before you've committed to it.",
    body: [
      "Most businesses judge a web designer on their portfolio and price. Both matter, but neither tells you what happens after the site launches, which is where a lot of disappointment quietly happens.",
      { h: "Worth asking directly" },
      {
        list: [
          "Do I own the domain and the code, or is it locked to your platform?",
          "Is SEO (sitemap submission, Google Business Profile setup) included, or extra?",
          "What happens if I want to leave in a year? Can I take the site with me?",
          "Who hosts it, and what happens if that server goes down?",
          "How do I make small content changes myself, if at all?",
          "What's included after launch: is support a one-off, or ongoing?",
        ],
      },
      { h: "The answer that should give you pause" },
      "Vagueness. A designer who can't clearly answer what happens to the site if you stop paying them, or who's evasive about whether you own the domain, is worth a second thought. Those are exactly the details that turn into a problem months later, not at signup.",
    ],
  },
  {
    slug: "free-website-builders-vs-custom-site",
    title: "Free Website Builders vs a Custom-Built Site",
    category: "Getting Started",
    metaDescription: "Wix, Squarespace and similar builders vs a custom-built site: the real trade-offs for a small local business.",
    publishDate: "2025-02-13",
    readTime: 4,
    excerpt: "The real trade-offs between a DIY builder and a custom build, not the marketing pitch either side gives you.",
    body: [
      "Both approaches work for some businesses. The trick is being honest about which trade-offs you're making.",
      { h: "What builders genuinely offer" },
      "Speed, low upfront cost, and full control if you're comfortable doing the work yourself. For a very simple presence, a single page with contact details, that can be entirely sufficient.",
      { h: "Where they typically fall short for local trades" },
      {
        list: [
          "Templated structure that's harder to fully optimise for specific local SEO",
          "Ongoing monthly fee regardless of whether you're actively using it",
          "Limited or no structured data (schema.org) support without technical workarounds",
          "Generic-looking sites that can blur together against competitors using the same templates",
        ],
      },
      { h: "What a custom build buys you" },
      "Full control over technical SEO, faster load times (no bloated builder framework), and a site that looks distinctly like your business rather than a recognisable template. Whether that's worth the higher cost depends on how much the website is expected to work for the business, versus just exist.",
    ],
  },
  {
    slug: "clear-call-to-action-matters",
    title: "Why a Clear Call-to-Action Matters More Than Fancy Design",
    category: "Conversion",
    metaDescription: "Why a clear, obvious call-to-action beats clever design every time, and the CTAs that convert for local businesses.",
    publishDate: "2025-03-13",
    readTime: 3,
    excerpt: "A beautiful site with a buried phone number loses to an ugly one with an obvious call button.",
    body: [
      "It's easy to spend all the design effort on how a site looks and none on what happens when someone's ready to act, and that's usually the more expensive mistake.",
      { h: "What a strong CTA looks like" },
      {
        list: [
          "One obvious primary action, not five competing buttons",
          "Language that matches intent: \"Call Now\" for urgent trades, \"Get a Quote\" for considered purchases",
          "Visible without scrolling, and ideally repeated further down the page",
          "A real tel: link on mobile, not just text that looks like a phone number",
        ],
      },
      { h: "The mistake that's easy to miss" },
      "A gorgeous hero section with no clear next step. Someone lands, likes what they see, and then has to hunt for how to get in touch, and a meaningful percentage simply won't bother hunting. The CTA isn't decoration; it's the entire point of the page existing.",
    ],
  },
  {
    slug: "turn-website-visitors-into-calls",
    title: "How to Turn Website Visitors Into Phone Calls",
    category: "Conversion",
    metaDescription: "Practical ways to increase the percentage of website visitors who pick up the phone or send an enquiry.",
    publishDate: "2025-04-10",
    readTime: 4,
    excerpt: "Traffic is only half the job. Here's what actually moves a visitor to pick up the phone.",
    body: [
      "Plenty of small business sites get a reasonable amount of traffic and still barely convert any of it into enquiries. Usually it's not a traffic problem; it's a conversion problem.",
      { h: "What tends to move the needle" },
      {
        list: [
          "Trust signals near the CTA: a star rating, a review count, \"fully insured\" if relevant",
          "Removing friction: a one-tap call button beats a contact form for urgent trades",
          "Specificity: \"Same-day quotes\" or \"30-45 min typical response\" beats vague reassurance",
          "Social proof close to the decision point, not buried on a separate testimonials page",
        ],
      },
      { h: "The WhatsApp effect" },
      "For a lot of local businesses, adding a WhatsApp option alongside a phone number measurably increases enquiries. Some customers, especially younger ones, will message before they'll call, and offering the lower-friction option captures people who'd otherwise just leave.",
      { h: "Test, don't assume" },
      "Small changes to button colour, wording, and position genuinely move conversion rates. If there's any way to track which pages people enquire from, it's worth watching over time rather than guessing once and leaving it.",
    ],
  },
  {
    slug: "should-you-add-online-booking",
    title: "Should You Add Online Booking to Your Trade Business?",
    category: "Conversion",
    metaDescription: "Whether online booking is worth adding for a trades business, and which tools (Google Calendar, Calendly) make it easy.",
    publishDate: "2025-05-15",
    readTime: 4,
    excerpt: "Not every trade needs it, but for appointment-based businesses, it quietly removes a lot of lost enquiries.",
    body: [
      "Online booking isn't universally necessary, but for anything appointment-based (a salon, a personal trainer, scheduled servicing) it solves a specific, common problem: enquiries that happen outside business hours.",
      { h: "The problem it solves" },
      "A customer browsing at 9pm who wants to book isn't going to call; the business is closed. Without a booking option, that intent just evaporates by morning, when they've often already found someone else. A booking widget captures that moment instead of losing it.",
      { h: "Tools that make it easy" },
      {
        list: [
          "Google Calendar integration: simple, free, works well for solo operators",
          "Calendly or similar: more features, still low cost, good for multiple staff/services",
          "Built into the site directly: most seamless, but needs proper setup to sync availability",
        ],
      },
      { h: "When it's not worth it" },
      "Emergency or highly variable work, like recovery or urgent repairs, doesn't really fit a booking calendar, since the whole point is immediate response. For those, a fast call button still beats booking software every time.",
    ],
  },
  {
    slug: "what-makes-a-good-about-us-page",
    title: "What Makes a Good About Us Page?",
    category: "Conversion",
    metaDescription: "Why the About page matters more than businesses think: for trust with customers and for AI answer engines alike.",
    publishDate: "2025-06-12",
    readTime: 3,
    excerpt: "An underrated page, for human trust, and increasingly for how AI tools describe your business too.",
    body: [
      "It's easy to treat the About page as an afterthought, but it does real work: it's often the second page an interested customer visits, right after checking your services.",
      { h: "What builds trust here" },
      {
        list: [
          "Who's behind the business: a name and a face, not just a company name",
          "Real experience: years in the trade, relevant qualifications, what led to starting the business",
          "Why the business does things differently, if it does",
          "Where you're based and who you serve",
        ],
      },
      { h: "The AI angle" },
      "This page also matters more than most business owners realise for how AI answer engines describe a business when asked about it. A clear, factual About page (paired with Organization schema) gives tools like ChatGPT and Google's AI Overviews something concrete to cite. A vague or missing About page leaves them with nothing accurate to work from.",
      "Skip the corporate-sounding filler. A short, honest, specific page beats a long, generic one every time, for customers and for AI alike.",
    ],
  },
  {
    slug: "mobile-first-website-design",
    title: "Mobile-First: Why Most of Your Customers Are on Their Phone",
    category: "Conversion",
    metaDescription: "Why mobile-first design matters for local business websites, and the specific things that break on mobile that don't on desktop.",
    publishDate: "2025-07-10",
    readTime: 4,
    excerpt: "For most local trades, mobile isn't a secondary experience. It's the primary one.",
    body: [
      "For local, service-based businesses, mobile traffic often makes up the clear majority of visits. Someone searching \"plumber near me\" is almost always doing it on a phone, often while dealing with the problem in real time.",
      { h: "What breaks on mobile that doesn't on desktop" },
      {
        list: [
          "Text too small to read without zooming",
          "Buttons too close together to tap accurately",
          "Phone numbers that aren't clickable tel: links",
          "Forms with too many fields for a small screen, causing drop-off",
          "Pop-ups or banners that cover the whole screen with no obvious close button",
        ],
      },
      { h: "Designing mobile-first, not mobile-adapted" },
      "There's a real difference between a site designed for mobile first (then scaled up) and a desktop site squeezed down to fit a phone. The second approach is where most of the above problems come from: content and layout decisions made for a big screen rarely translate cleanly to a small one without real rework.",
      "Google's own ranking system now primarily evaluates the mobile version of a site (mobile-first indexing), so this isn't just a user-experience issue; it directly affects rankings too.",
    ],
  },

  // ─── 2025 (H2) — GEO & AEO ──────────────────────────────────────────────
  {
    slug: "what-is-geo-generative-engine-optimisation",
    title: "What Is GEO (Generative Engine Optimisation) and Why It's the Next Big Thing",
    category: "GEO & AEO",
    metaDescription: "GEO explained: how generative engine optimisation differs from traditional SEO, and why local businesses should start paying attention now.",
    publishDate: "2025-08-14",
    readTime: 5,
    excerpt: "SEO gets you ranked. GEO is about showing up when AI tools generate an answer instead of a results page.",
    body: [
      "GEO, generative engine optimisation, is the newer discipline sitting alongside SEO, focused on how a business shows up not in a list of blue links, but inside an AI-generated answer.",
      { h: "How it's different from traditional SEO" },
      "Traditional SEO optimises for ranking position in a results page a human scans through. GEO optimises for being included, referenced, or recommended when an AI tool synthesises an answer, often without the user clicking through to any website at all. The goal shifts from \"rank #1\" to \"be the source the AI uses.\"",
      { h: "Why this matters for local businesses specifically" },
      {
        list: [
          "Local searches increasingly get answered directly inside AI Overviews without a click",
          "Voice assistants and AI chat tools are being used more for \"find me a [trade] near me\" queries",
          "Being the cited source in an AI answer is arguably more valuable than a lower organic ranking, since it's presented as a direct recommendation",
        ],
      },
      { h: "What helps" },
      "Much of it overlaps with strong local SEO: accurate structured data, clear factual content, genuine reviews. But GEO also rewards content structured for extraction: clear headings, direct answers to specific questions, and information an AI system can lift cleanly rather than infer from vague marketing copy.",
      "This is still an emerging area, and the businesses paying attention now have a real head start over the ones who'll only start caring once it's mainstream.",
    ],
  },
  {
    slug: "what-is-aeo-answer-engine-optimisation",
    title: "What Is AEO? Getting Your Business Quoted by ChatGPT and AI Overviews",
    category: "GEO & AEO",
    metaDescription: "AEO explained simply: how to structure a website so AI answer engines like ChatGPT and Google AI Overviews can cite your business directly.",
    publishDate: "2025-09-11",
    readTime: 5,
    excerpt: "How to structure a site so ChatGPT, Perplexity and Google's AI Overviews can cite your business by name.",
    body: [
      "AEO, answer engine optimisation, is about making a website easy for AI systems to read, trust, and quote directly when someone asks a question the business could answer.",
      { h: "The concrete things that help" },
      {
        list: [
          "FAQ schema (FAQPage structured data): one of the clearest, most direct signals an AI system can lift a Q&A from",
          "Organization/LocalBusiness schema: gives AI tools a structured, trustworthy fact-base about the business",
          "Clear, direct answers to specific questions in the actual page content, not just marketing language",
          "An llms.txt file: an emerging plain-English summary aimed specifically at AI crawlers",
          "A genuine About page and transparent business information",
        ],
      },
      { h: "Why this is worth doing now rather than later" },
      "Almost no small local businesses have done any of this yet, which means the ones who do are disproportionately likely to be the ones AI tools cite, simply because there's so little well-structured competition for these signals right now. That gap won't stay open forever.",
      { h: "The mindset shift" },
      "Write content the way you'd answer the question if someone asked you directly, out loud: clear, specific, no fluff. That's exactly the shape AI systems are built to lift and quote.",
    ],
  },
  {
    slug: "will-ai-search-replace-google",
    title: "Will AI Search Replace Google for Local Businesses?",
    category: "GEO & AEO",
    metaDescription: "Whether AI search tools like ChatGPT will replace Google for local business discovery, and what it means either way.",
    publishDate: "2025-10-09",
    readTime: 4,
    excerpt: "Probably not entirely, and probably not soon, but the trend is real enough to plan for either way.",
    body: [
      "It's a genuinely open question, and anyone claiming certainty either way is overselling their confidence. What's clearer is the direction of travel, even if the timeline and final shape aren't settled.",
      { h: "What's changing" },
      "A growing share of searches, especially informational and comparison-type ones, are increasingly answered directly by AI, without a click to any website. Google's own AI Overviews sit right inside its search results now, reducing clicks to the organic listings beneath them.",
      { h: "What probably isn't changing soon" },
      "Local, transactional intent (\"book a plumber now,\" \"call a recovery service\") still tends to route through Maps and traditional local search, because those searches need real-time, location-specific, actionable results: something AI chat answers aren't naturally built to replace yet.",
      { h: "The practical approach" },
      "Don't bet everything on either horse. Traditional local SEO (Google Business Profile, reviews, local content) and AEO/GEO signals (structured data, FAQ schema, clear factual content) overlap heavily anyway, so doing both well covers the business regardless of how search evolves over the next few years.",
    ],
  },
  {
    slug: "what-is-llms-txt",
    title: "What Is llms.txt and Should Your Website Have One?",
    category: "GEO & AEO",
    metaDescription: "llms.txt explained: the emerging convention for helping AI crawlers understand a business, and how to add one.",
    publishDate: "2025-11-13",
    readTime: 3,
    excerpt: "A new, simple convention aimed squarely at AI crawlers, and almost nobody local has one yet.",
    body: [
      "llms.txt is an emerging (and still informal) convention: a plain-text file at yourdomain.com/llms.txt that gives AI crawlers a clear, structured summary of what a business does, in language built for machines to parse rather than humans to browse.",
      { h: "How it's different from a normal page" },
      "A homepage is written to persuade a human visitor. An llms.txt file is written to inform an AI system quickly and unambiguously: services offered, location, key facts, without marketing language getting in the way of a clean answer.",
      { h: "What a basic one looks like" },
      "Typically: business name, a one-line description, the services offered, the areas served, and links to the most important pages (services, contact, pricing), kept short and factual.",
      { h: "Is it worth doing now?" },
      "It costs almost nothing to add, and because it's still new, very few competitors, especially local ones, have bothered yet. Whether it becomes a major ranking factor or a quiet niche convention, being early costs nothing and has no real downside.",
    ],
  },
  {
    slug: "faq-schema-and-ai-answer-engines",
    title: "How FAQ Schema Helps AI Recommend Your Business",
    category: "GEO & AEO",
    metaDescription: "Why FAQ structured data (FAQPage schema) is one of the clearest ways to get quoted by AI search tools, and how to add it.",
    publishDate: "2025-12-11",
    readTime: 4,
    excerpt: "One of the clearest, most direct ways to get lifted and quoted by an AI answer, rather than just ranked.",
    body: [
      "FAQPage structured data (a specific type of schema.org markup) turns a normal-looking FAQ section into something search engines and AI tools can parse as discrete, clearly-labelled question-and-answer pairs, rather than a wall of unstructured text.",
      { h: "Why that structure matters" },
      "AI systems generating an answer need to extract a clean, specific fact or explanation. A well-marked-up FAQ answer, \"How much does a website cost?\" paired with a direct, specific answer, is exactly the shape that's easy to lift cleanly and attribute back to the source.",
      { h: "What makes a good FAQ entry for this purpose" },
      {
        list: [
          "A real question a customer would type or ask out loud",
          "A direct, specific answer in the first sentence, not a windup before the point",
          "No vague hedging (\"it depends on many factors\") without at least a concrete range or example",
        ],
      },
      { h: "The double benefit" },
      "This isn't purely an AI play: the same FAQPage schema can also earn expandable rich results directly in regular Google search, taking up more visual space in the results page. It's rare to find an SEO tactic that helps with both traditional rankings and AI citation this directly, but FAQ schema does both.",
    ],
  },

  // ─── 2026 — Recent, choosing a designer, local & case studies ─────────
  {
    slug: "how-to-choose-a-web-designer-in-glasgow-2026",
    title: "How to Choose a Web Designer in Glasgow in 2026",
    category: "Getting Started",
    metaDescription: "What to look for when choosing a web designer in Glasgow in 2026, beyond portfolio and price.",
    publishDate: "2026-01-15",
    readTime: 5,
    excerpt: "Portfolio and price are the easy things to compare. Here's what actually separates a good hire from a bad one.",
    body: [
      "Glasgow has no shortage of web designers and agencies to choose from, which makes the decision harder, not easier: everyone's portfolio looks reasonable at a glance.",
      { h: "What to look for in 2026" },
      {
        list: [
          "Do they talk about SEO/GEO/AEO as a baseline, not an expensive add-on? By now, this should be standard, not a premium upsell.",
          "Can they show real, verifiable results, not just \"we built a nice-looking site\" but actual before/after numbers for a real client",
          "Do they understand your specific trade, or are they applying a generic template to every business regardless of industry?",
          "Is there an ongoing relationship (monthly plan, regular updates) or a one-and-done handover with no support after launch?",
        ],
      },
      { h: "Red flags worth taking seriously" },
      "Vague answers about SEO (\"we do SEO\" with no specifics), no mention of Google Business Profile at all, pressure to sign quickly, and an unwillingness to show real client results rather than generic stock-photo portfolio pieces.",
      { h: "The Glasgow-specific angle" },
      "A designer who genuinely knows the local area, the towns, the trades landscape, the local competition, will build local SEO into the site far more effectively than someone applying a one-size-fits-all national template. Local knowledge isn't decoration here; it directly shapes which pages, keywords and structured data matter for your specific area.",
    ],
  },
  {
    slug: "location-pages-for-trades-businesses",
    title: "How Location Pages Help Trades Businesses Rank in More Areas",
    category: "SEO",
    metaDescription: "Why dedicated location pages (not just an 'areas we cover' list) help trades businesses rank across multiple towns.",
    publishDate: "2026-02-12",
    readTime: 4,
    excerpt: "A single 'areas we cover' list ranks for none of them well. Dedicated pages are what actually work.",
    body: [
      "A common but weak pattern: one page listing ten towns a business serves, with a sentence each. It reads fine to a human, but does very little for search. Google generally can't rank one thin page for ten different local searches simultaneously.",
      { h: "What works instead" },
      "A dedicated page per town or area, each with genuinely specific local content, not just the town name swapped into a template sentence, but real local detail: postcodes, nearby landmarks, specific roads, and what makes that particular area's service needs distinct if anything does.",
      { h: "The trap to avoid" },
      { quote: "\"We provide [service] in [town]. Call us today.\" repeated 15 times with only the town name changed is exactly what Google's algorithms are built to detect and discount." },
      "Thin, near-duplicate location pages can do more harm than the single combined page they replaced. Each page needs to earn its place with genuinely different, useful content.",
      { h: "How to do it properly" },
      {
        list: [
          "Real local detail specific to that area, not generic filler",
          "A mention of nearby towns, to build a natural internal-linking network",
          "Local pricing or response-time detail if it genuinely varies by area",
          "Photos or reviews specifically mentioning that location, if available",
        ],
      },
      "Done properly, this is one of the most reliable ways for a service-area business to expand its reach across many towns without diluting quality. It just takes real content, not a find-and-replace exercise.",
    ],
  },
  {
    slug: "rank-higher-on-google-maps",
    title: "How to Rank Higher on Google Maps for Your Trade",
    category: "SEO",
    metaDescription: "The specific factors that determine local pack rankings on Google Maps, and what a business can actually control.",
    publishDate: "2026-03-12",
    readTime: 5,
    excerpt: "The three-pack that shows up above the normal results. Here's what actually determines who's in it.",
    body: [
      "The \"local pack\" (the three business listings with a map that show up for local searches) is some of the most valuable real estate in local search, and the ranking factors behind it are reasonably well understood.",
      { h: "The three main factors" },
      {
        list: [
          "Relevance: does the business's category and content genuinely match the search",
          "Distance: proximity between the searcher and the business location",
          "Prominence: how well-known and well-reviewed the business is, both on and off Google",
        ],
      },
      { h: "What's within a business's control" },
      "Distance mostly isn't (short of opening a second location), but relevance and prominence very much are. A fully completed Business Profile with the right categories, consistent NAP (name/address/phone) details across the web, a strong and growing review base, and a website with matching local SEO all move prominence and relevance directly.",
      { h: "A detail people miss" },
      "Category selection matters more than most business owners realise. A garage that only selects \"Car repair\" but also does MOTs, tyres, and diagnostics is missing out on searches specific to those secondary categories. Adding accurate secondary categories widens which searches the profile can surface for.",
    ],
  },
  {
    slug: "getting-found-online-renovation-business",
    title: "Getting Found Online as a Renovation or Trades Business",
    category: "Industry Guides",
    metaDescription: "How renovation, joinery and building trades businesses should approach their online presence to win more high-value jobs.",
    publishDate: "2026-04-09",
    readTime: 4,
    excerpt: "Renovation is a considered, high-value purchase. The marketing needs to match how customers actually decide.",
    body: [
      "Unlike an emergency-response trade, renovation and building work is usually a considered purchase: customers research, compare, and take their time before committing. That changes what needs to be on the site.",
      { h: "What matters most for this category" },
      {
        list: [
          "A genuine portfolio: real before/after project photos, ideally with some project detail (scope, rough timeline)",
          "Trust signals: insurance, qualifications, guarantees, years trading",
          "Clear service breakdown (kitchens, bathrooms, extensions, joinery) rather than one vague \"renovations\" catch-all",
          "A straightforward quote-request process, since price is rarely listed upfront for bespoke work",
        ],
      },
      { h: "The SEO angle" },
      "Searches here tend to be more specific and less urgent, \"kitchen renovation Glasgow\" rather than \"emergency plumber near me.\" That means content quality and depth matter more relative to sheer speed of response; a genuinely detailed portfolio page can outperform a barebones site even if the barebones one loads faster.",
      { h: "Reviews still matter, differently" },
      "For a big-ticket, considered purchase, customers often read reviews in more depth, not just checking the star average, but reading several full reviews for reassurance before a five-figure commitment. Encouraging customers to leave a genuinely detailed review (not just a rating) pays off more here than in faster-turnaround trades.",
    ],
  },
  {
    slug: "local-food-businesses-selling-online",
    title: "How Local Food Businesses Can Sell Online",
    category: "Industry Guides",
    metaDescription: "How independent butchers, bakers and food businesses can build a genuine online ordering presence, based on real client results.",
    publishDate: "2026-05-14",
    readTime: 5,
    excerpt: "Independent food businesses moving online face a specific set of decisions. Here's what matters, based on a real result.",
    body: [
      "Independent butchers, bakers, and specialist food shops moving online face a different set of questions than a service trade: this is genuine e-commerce, not a lead-generation site.",
      { h: "What an online food store needs" },
      {
        list: [
          "Real product listings, not a generic \"see in-store for our range\" page",
          "Delivery and pickup options clearly explained, including areas covered for delivery",
          "Product-level structured data (Product schema) so search engines and shopping surfaces can show price and availability directly",
          "An easy, low-friction checkout: cart abandonment is a genuine risk if the process feels clunky",
        ],
      },
      { h: "A real result worth mentioning" },
      "One local butcher with zero prior online presence launched a proper online store and made over £7,000 in online sales within the first month, across 143 paid orders: a concrete example of what's achievable when a genuinely functional store replaces \"see us in person only.\"",
      { h: "What made the difference" },
      "Not a single trick, but a combination of real product listings, easy delivery/pickup selection, and making the store easy to find via local SEO from day one. None of it was complicated; it just needed to exist and work properly, which for a lot of small food businesses it simply doesn't yet.",
    ],
  },
  {
    slug: "case-study-local-butcher-online-sales",
    title: "Case Study: How a Local Butcher Made £7,298 Online in One Month",
    category: "Case Studies",
    metaDescription: "A real case study: how a local butcher with no prior online presence made £7,298 across 143 orders in their first month online, with a full breakdown of the numbers.",
    publishDate: "2026-06-11",
    readTime: 7,
    excerpt: "A full breakdown of a real result: £7,298 across 143 orders in the first month, from a standing start, with the actual numbers.",
    body: [
      "This one's a genuine case study, not a hypothetical: a local independent butcher and fishmonger with no online store or website presence before, taken from zero to a functioning e-commerce site. Every number in this post is pulled directly from the store's own order dashboard, not rounded up or estimated for effect.",
      { h: "The starting point" },
      "No website, no online ordering, entirely walk-in and phone-order based. Like a lot of independent food businesses built on genuine local reputation, all trade depended on people already knowing the shop existed and being physically nearby: a loyal customer base, but a hard ceiling on how far it could reach. Someone two streets over who'd never walked past the shop had no way to find it.",
      {
        chart: {
          title: "Online revenue: before vs. first month",
          bars: [
            { label: "Before (no online store)", value: 0, prefix: "£" },
            { label: "First month online", value: 7298, prefix: "£" },
          ],
        },
      },
      { h: "What was actually built" },
      {
        list: [
          "A full online store with real product listings: 191 individual products, not a generic \"see in-store for our range\" placeholder page",
          "Both delivery and pickup options, so customers could choose whichever suited them",
          "Active promotions built into the store (3 running at launch) to give people a reason to try ordering online for the first time",
          "Local SEO from day one, so the business could be found by people who didn't already know it existed, not just repeat custom finding a new way to order",
        ],
      },
      { h: "The first month, in full" },
      "This is the part most case studies gloss over with a single headline number. Here's the complete picture, straight from the store's own dashboard:",
      {
        chart: {
          title: "First month: full breakdown",
          bars: [
            { label: "Total revenue", value: 7298, prefix: "£" },
            { label: "Paid orders", value: 143 },
            { label: "Average order value", value: 51, prefix: "£" },
            { label: "Products listed", value: 191 },
          ],
        },
      },
      "£7,298.87 across 143 paid orders works out to an average order value of just over £51, a healthy basket size for a butcher and fishmonger, and a strong early signal that customers weren't just testing the water with a single small order. A mix of delivery and pickup orders came through from day one, suggesting the flexibility of offering both genuinely mattered rather than one option carrying the whole store.",
      { h: "Why this worked, specifically" },
      "Three things came together, and it's worth being precise about which ones mattered rather than crediting the whole thing to \"a nice website\":",
      {
        list: [
          "Real local demand that already existed but had no digital outlet: the business wasn't starting from zero reputation, just zero online reach",
          "A genuinely functional store, not a brochure site with a phone number: customers could complete a purchase in a few taps",
          "Local SEO from launch, meaning the store was findable by new customers immediately rather than needing months to be discovered",
        ],
      },
      { quote: "The business wasn't missing customers. It was missing a way for existing local demand to convert into an order without someone physically walking into the shop." },
      { h: "What this doesn't mean" },
      "Not every business will see an identical number: product type, existing local reputation, competition, and how much pent-up local demand exists all vary hugely. A launch month is also typically a business's most enthusiastic marketing push, so month two and three are the more telling test of whether this becomes a genuine ongoing channel rather than a one-off spike. What this case does show clearly is the size of the gap that can exist between \"good local reputation\" and \"reachable by anyone who doesn't already know you,\" and how quickly that gap can close once it's addressed.",
    ],
  },
  {
    slug: "case-study-23-to-40-google-reviews",
    title: "Case Study: Going From 23 to 40 Google Reviews in 12 Hours",
    category: "Case Studies",
    metaDescription: "A real case study on how automated review requests took one client from 23 to 40 Google reviews in 12 hours, and to the #1 local ranking, with the full mechanics of why it worked.",
    publishDate: "2026-07-09",
    readTime: 6,
    excerpt: "23 to 40 Google reviews in 12 hours, and on to the #1 local ranking. The full mechanics of what drove it, not just the headline.",
    body: [
      "Review growth is usually gradual: a slow trickle over months as happy customers occasionally remember to leave one. This case is a genuine outlier worth breaking down properly, because the mechanism behind it is repeatable and explainable, not luck or a fluke of timing.",
      { h: "What happened" },
      "A client went from 23 to 40 Google reviews in roughly 12 hours, a jump that would normally take several months at a typical organic pace of a review or two a week.",
      {
        chart: {
          title: "Google reviews, before vs. after (12 hours)",
          bars: [
            { label: "Before", value: 23 },
            { label: "After", value: 40 },
          ],
          note: "A net increase of 17 reviews in roughly half a day, equivalent to several months of typical organic review growth for a business this size.",
        },
      },
      { h: "What drove it" },
      "An automated review-request process, sent systematically after every completed job rather than left to chance, memory, or whoever happened to be free to ask that day. That's the entire mechanism; there's no trick beyond consistency and timing:",
      {
        list: [
          "Every completed job triggers a request automatically: nothing depends on a staff member remembering to ask",
          "The request goes out immediately after the job, while satisfaction is at its highest point, not days later once the moment has passed",
          "The link goes straight to the review form: no extra steps, no searching for the business on Google first",
          "It's sent via the channel customers actually respond to (text/WhatsApp tends to outperform email significantly for this)",
        ],
      },
      { h: "Why 12 hours specifically, not 12 weeks" },
      "The speed here isn't really about the mechanism being unusually powerful; it's about what it revealed. There was a genuine backlog: real customers who'd had a good experience but had never been asked, or been asked too long after the fact to bother. Automating the request didn't create new satisfied customers out of nowhere. It captured a batch of goodwill that had been sitting there unclaimed, all at once, because the ask had never been consistent before.",
      { h: "The follow-on effect on rankings" },
      "That jump in review count directly contributed to the business becoming the #1 ranked result in their area on Google, a concrete, visible demonstration of how directly review count and recency feed into local pack rankings, not just customer trust at the point of decision. Google's local ranking algorithm weighs review signals heavily, and a sudden, genuine burst of recent reviews is exactly the kind of prominence signal that moves a listing up.",
      { quote: "The mechanism is simple enough to repeat: ask every time, immediately, with minimal friction. The 12-hour jump was a backlog being cashed in, not a one-off event." },
      { h: "Why this doesn't fade the way paid tactics do" },
      "Unlike a one-off review push or a paid ad campaign, this is a standing process: it doesn't stop working after the initial backlog clears. Every new job still triggers a request, so the review count keeps climbing at a steady, sustainable pace long after the initial surge, rather than spiking once and then flatlining.",
      { h: "The honest caveat" },
      "Not every business has 17 reviews' worth of unclaimed goodwill sitting in a backlog waiting to be asked. A newer business or one with fewer completed jobs won't see a jump this size this fast, because there isn't yet a backlog to draw on. What every business with a track record of good work does have, though, is some version of this gap: satisfied customers who were never properly asked. Closing that gap is what moved the needle here, not a clever growth hack.",
    ],
  },
  {
    slug: "why-weekly-seo-reporting-matters",
    title: "Why Weekly SEO Reporting Beats a One-Off Website Build",
    category: "SEO",
    metaDescription: "Why ongoing, weekly SEO reporting and upgrades outperform a one-time website build with no follow-up.",
    publishDate: "2026-08-13",
    readTime: 4,
    excerpt: "A website is a starting point, not a finish line. Here's why the ongoing work is where the real gains come from.",
    body: [
      "A common assumption: build the site once, done. In practice, the businesses that see rankings and enquiries climb over time are almost always the ones treating the website as an ongoing project, not a one-time purchase.",
      { h: "What changes without ongoing attention" },
      {
        list: [
          "Competitors add new pages, reviews, and content: a static site slowly falls behind, even if nothing on it is technically broken",
          "Search algorithms and AI answer-engine behaviour genuinely shift over time: what worked at launch can quietly stop working",
          "Technical issues (broken links, expired plugins, slow-loading new content) accumulate unnoticed without regular checks",
        ],
      },
      { h: "What weekly reporting catches" },
      "Real, specific signals: a noindex tag accidentally left on, a new local competitor pulling ahead on reviews, a page that's started loading slowly, a genuine content gap versus what's ranking nearby. None of that shows up from a one-off build; it only shows up from someone watching.",
      { h: "The compounding effect" },
      "Small, consistent improvements, a new location page here, a review push there, a technical fix caught early, compound over months in a way a single launch-day effort never can. The businesses pulling ahead in competitive local markets are rarely the ones with the fanciest initial build; they're the ones that never stopped improving it.",
    ],
  },
  {
    slug: "case-study-sl-detailing-booking-system",
    title: "Case Study: Moving SL Detailing Off Google Calendar and Onto a Real Booking System",
    category: "Case Studies",
    metaDescription: "How SL Detailing's booking process went from a shared Google Calendar to a full online booking system with instant customer and owner notifications, plus an automatic review request after every job.",
    publishDate: "2026-08-19",
    readTime: 5,
    excerpt: "From a shared Google Calendar to a proper booking system: instant confirmations, owner notifications, and an automatic review request the moment a job's done.",
    body: [
      "SL Detailing launched with a straightforward website and a Google Calendar for taking bookings. Simple to set up, and a perfectly sensible place to start; a lot of small service businesses begin exactly there. This is what changed once it started to strain, and what replaced it.",
      { h: "Where it started" },
      "A customer requested a slot, it went into the calendar, and the owner checked it manually before confirming. No database, no automation, just a shared calendar doing a job it was never really built for.",
      { h: "Where it started to strain" },
      {
        list: [
          "Every booking needed manual entry and a manual check for clashes",
          "Customers had no automatic confirmation, so they weren't always sure a slot had actually been locked in",
          "Nothing connected 'job finished' to anything happening next, like asking for a review",
          "A calendar has no concept of a customer record, so there was no history of who'd booked before or how often",
        ],
      },
      {
        compare: {
          title: "Booking process, before and after",
          before: {
            label: "Google Calendar",
            points: [
              "Manual entry for every booking",
              "No automatic confirmation to the customer",
              "No record of repeat customers",
              "Nothing happens automatically once a job's marked done",
            ],
          },
          after: {
            label: "Full booking system",
            points: [
              "Customers book directly and get instant confirmation",
              "Every booking stored in a proper database, not a shared calendar",
              "The owner is notified the moment a new booking comes in",
              "An automatic email goes out after the job asking for a Google review",
            ],
          },
        },
      },
      { h: "How the new system works" },
      "Five steps, and every one of them fires without anyone needing to remember to do it:",
      {
        flow: {
          title: "What happens automatically, start to finish",
          steps: [
            { title: "Customer books online", description: "They pick a service and time slot directly on the site; no phone call or message needed to lock it in." },
            { title: "Instant confirmation", description: "The customer gets an immediate notification confirming the booking, so there's no uncertainty about whether it went through." },
            { title: "Owner notified straight away", description: "SL Detailing's owner is notified the moment a new booking lands, with no need to keep checking a calendar." },
            { title: "Job marked complete", description: "Once the job's done and marked complete in the system, nothing further needs to be remembered or chased." },
            { title: "Automatic review request", description: "An email goes out asking the customer to leave a Google review, sent while the job's still fresh rather than left to chance." },
          ],
        },
      },
      { h: "Why the review step matters" },
      "Consistent, automatic review requests are one of the most reliable ways a small business grows its Google presence: review count and recency feed directly into local search rankings, and a request sent the moment satisfaction is highest converts far better than one sent days later, if it's sent at all. Building it into the system means it never depends on someone remembering to ask.",
      { quote: "The booking system doesn't just save time on admin. It closes the loop between 'job done' and 'ask for a review', the step most businesses mean to do and forget." },
      { h: "The honest read" },
      "This one's a process case study, not a stats one: there's no single headline number to point at, because the win is structural. Fewer missed or double-booked slots, less manual admin, and a review request that fires every single time instead of whenever someone remembers. That last part compounds quietly in the background, and it's exactly the kind of thing that's easy to skip when it depends on memory and easy to keep when it doesn't.",
    ],
  },
  {
    slug: "case-study-envirocycle-glasgow-search-traffic",
    title: "Case Study: Envirocycle Glasgow, Three Months of Real Search Data",
    category: "Case Studies",
    metaDescription: "A real Google Search Console case study for Envirocycle Glasgow: 321 clicks and 39.5k impressions over three months, and what an average position of 12.6 actually means.",
    publishDate: "2026-09-02",
    readTime: 5,
    excerpt: "Straight from Google Search Console: 321 clicks, 39.5k impressions, three months in. What those numbers mean, and what happens next.",
    body: [
      "This one's pulled straight from Envirocycle Glasgow's own Google Search Console, not a projection or a rounded-up estimate. It's also an honest mid-story update rather than a finished result: local SEO compounds over months, and three months in is early, not the end of the process.",
      { h: "The numbers, as they stand" },
      {
        chart: {
          title: "Google Search performance, last 3 months",
          bars: [
            { label: "Total impressions", value: 39500 },
            { label: "Total clicks", value: 321 },
          ],
          note: "Average CTR of 0.8% and an average position of 12.6 across all queries for the period, both pulled directly from Search Console.",
        },
      },
      "An average position of 12.6 sits on page two of Google, not page one. That's the honest headline: the site is being shown to real searchers thousands of times a month, and the next stage of the work is turning that mid-page-two visibility into top-of-page-one, where click-through stops sitting at 0.8% and starts climbing properly.",
      { h: "What the trend actually shows" },
      "Chart the same window day by day and the direction matters more than any single day's number. Both clicks and impressions were close to flat at the start of the period and were running at multiples of that by the end of it: the shape of a listing that's actively climbing, not one that's plateaued.",
      { h: "What actually moves a number like this" },
      {
        list: [
          "Local SEO fundamentals aimed at what people actually search for, not just the business's own name",
          "A Google Business Profile kept active and accurate, since Maps and web search overlap heavily for local queries",
          "Technical checks every week, catching slow pages, broken links or indexing issues before they cost rankings",
          "No one-off launch and walk away; continuous work, since search position moves in small increments, not a single jump",
        ],
      },
      { quote: "39.5k impressions is real demand already finding the listing. The job now is converting more of that page-two visibility into page-one clicks." },
      { h: "The honest caveat" },
      "Three months of data is a real result, not a hypothetical, but it's not the ceiling either. An average position of 12.6 is a mid-campaign number for a business partway through gaining ground, and it's being tracked and reported on weekly rather than left to check itself. The number worth watching next isn't the position average dropping to single digits overnight; it's whether the trend line in this chart keeps climbing the way it has for the last three months.",
    ],
  },
];

export const postSlugs = posts.map((p) => p.slug);
